export enum ActionType {
  SET_COORDINATES = "SET_COORDINATES",
  SET_ACTIVE_VIEW = "SET_ACTIVE_VIEW",
  GET_OPEN_FORECAST = "GET_OPEN_FORECAST",
  GET_LOCATION_DATA = "GET_LOCATION_DATA",
  SET_SLICED_HOURLY_FORECAST = "SET_SLICED_HOURLY_FORECAST",
}
